---
title: "Flink vs. Spark"
bibliography: bib.yaml
csl: iso690-author-date-de.csl
subtitle: ""
lang: de-DE
format:
  revealjs:
    slide-number: true
    theme: league
---

## Literatur

[@Sakr_HandbookBig_2017, 219\psqq]

[@Kleppmann_DesigningDataIntensive_2017, 439\psqq]

## Warum Stream Processing?

- Fraud detection systems need to determine if the usage patterns of a credit card have unexpectedly changed, and block the card if it is likely to have been stolen.
- Trading systems need to examine price changes in a financial market and execute trades according to specified rules.
- Manufacturing systems need to monitor the status of machines in a factory, and quickly identify the problem if there is a malfunction.
- Military and intelligence systems need to track the activities of a potential aggressor, and raise the alarm if there are signs of an attack.
[@Kleppmann_DesigningDataIntensive_2017, 465]

## 

Dataflow Engines

## Spark Structured Streaming {auto-animate=true}



## {auto-animate=true}

Spark

(Structured)

Streaming 

## Spark -- Facts

Abstraktion
- inkrementelle Verarbeitung
- Checkpointing
- Watermarks

## Spark

::::: {.columns}

::::: {.column width="50%"}

### ++

Batch-API = Streaming-API (DataFrames und Datasets)

Batch-Engine ≅ Streaming-Engine


:::::

::::: {.column width="50%"}

### --



:::::

:::::
## Flink -- Facts

## Flink -- Stärken und Schwächen
